### ISSUE TITLE
Project Overview

### ISSUE THREAD

**Issue by Neskoff** [Neskoff/tsw-selenium-java#1]

**Comment by Neskoff** [comment]
- [x] Add external dependencies and implement a login test case #2
- [x] Implement constants to simulate .env file #4
- [x] Remove unused imports #6
- [x] Implement register test case #8
- [x] Implement user details validation #10
- [x] Implement adding items test case #12
- [x] Implement item sum test #14
- [x] Implement test suite #16
